#!/bin/sh

echo "Starting Destiny I installation..."
echo 
echo "[1/4] Downloading Forge Server from official site..."
wget -O forge_installer.jar https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-installer.jar && \
echo "[2/4] Installing Forge Server..." && \
java -jar forge_installer.jar --installServer && \
echo "[3/4] Removing Forge Installer Data..." && \
rm forge_installer.ja* && \
echo "[4/4] Renaming Installed Server jar to server.jar..." && \
mv forge* server.jar && \
echo
echo "Server Installation Complete"
